---
Name: cdnservices
---
Injector:
  ThemeCdn:
    properties:
      contentDelivery: %$ContentDeliveryService
      contentService: %$ContentService
  CdnControllerExtension:
    properties:
      contentDelivery: %$ContentDeliveryService
      contentService: %$ContentService

---
name: extensions
---
Image_Cached:
  extensions:
    - SilverStripeAustralia\ContentServiceAssets\ImageCachedExtension
#
#Upload:
#  extensions:
#    - SilverStripeAustralia\ContentServiceAssets\UploadExtension

---
name: injector
---
Injector:
  SilverStripeAustralia\ContentServiceAssets\ImageBackend:
    factory: SilverStripeAustralia\ContentServiceAssets\ImageBackendFactory
  SilverStripeAustralia\ContentServiceAssets\ImageBackendFactory:
    constructor:
      - "GDBackend"
  SilverStripeAustralia\ContentServiceAssets\ImageCachedExtension:
    constructor:
      - %$ContentService
  SilverStripeAustralia\ContentServiceAssets\VersionedFileExtension:
    constructor:
      - %$ContentService
---
name: versioned_files
only:
  moduleexists: versionedfiles
---
File:
  extensions:
    - SilverStripeAustralia\ContentServiceAssets\VersionedFileExtension

---
Name: cdn_image_settings
---
File:
  class_for_file_extension: 
    jpg: CdnImage
    jpeg: CdnImage
    png: CdnImage
    gif: CdnImage
    bmp: CdnImage

---
Name: cdn_routes
---
Director:
  rules:
    'cdnassets/$ID': 'CDNSecureFileController'